---
- name: Install docker
  hosts: docker
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: get docker-compose
      get_url:
      url: "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: install docker-compose stuff with pip
      pip:
        name: " {{ item }}"
      with_items:
        - pyyaml
        - docker-py
        - docker-compose       

