version: '2'
services:

  #Elif Service
  elif-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: elif-app
    restart: unless-stopped
    ports:
      - '5000:5000'
    depends_on:
     - elif-sql

  nginx:
    image: nginx:stable-alpine
    container_name: elif-nginx
    ports:
      - '80:80'
    depends_on:
      - elif-app
    volumes:
      - ./nginx:/etc/nginx/

  #MySQL Service
  elif-sql:
    image: mysql
    container_name: elif-sql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sizes
      MYSQL_ROOT_PASSWORD: Elolof19
    volumes:
      - ./data:/docker-entrypoint-initdb.d
