ALTER USER root IDENTIFIED WITH mysql_native_password BY 'Elolof19';

CREATE DATABASE IF NOT EXISTS `sizes`;

USE `sizes`;

DROP TABLE IF EXISTS `sizes`;

CREATE TABLE `sizes` ( id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, kilo VARCHAR(30) NOT NULL, boy VARCHAR(30) NOT NULL, reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP );
